// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtpreMjL9e4oU5VKk38AdMyG635rSNzzM',
    appId: '1:1060803862388:web:c2ac77e12c788b54b41621',
    messagingSenderId: '1060803862388',
    projectId: 'derma-institute-7ea18',
    authDomain: 'derma-institute-7ea18.firebaseapp.com',
    storageBucket: 'derma-institute-7ea18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA52qtq77Xp3_XwFuEKU56gvkhf-SYc7tc',
    appId: '1:1060803862388:android:9fae37ddbb179270b41621',
    messagingSenderId: '1060803862388',
    projectId: 'derma-institute-7ea18',
    storageBucket: 'derma-institute-7ea18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60gp80_qZFXPzrOliAOHmsdMkUTDcqVY',
    appId: '1:1060803862388:ios:ad1aec0a9e6b3f1cb41621',
    messagingSenderId: '1060803862388',
    projectId: 'derma-institute-7ea18',
    storageBucket: 'derma-institute-7ea18.firebasestorage.app',
    iosBundleId: 'com.dermainstitute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60gp80_qZFXPzrOliAOHmsdMkUTDcqVY',
    appId: '1:1060803862388:ios:43c9c03c5916c8a3b41621',
    messagingSenderId: '1060803862388',
    projectId: 'derma-institute-7ea18',
    storageBucket: 'derma-institute-7ea18.firebasestorage.app',
    iosBundleId: 'com.example.dermainstitute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtpreMjL9e4oU5VKk38AdMyG635rSNzzM',
    appId: '1:1060803862388:web:7db9922efb5af381b41621',
    messagingSenderId: '1060803862388',
    projectId: 'derma-institute-7ea18',
    authDomain: 'derma-institute-7ea18.firebaseapp.com',
    storageBucket: 'derma-institute-7ea18.firebasestorage.app',
  );
}
